// Flight-based terminology for FlightDeck OS (display labels only; URLs unchanged)
export const FLIGHT_TERMS = {
  OVERVIEW: 'Flight Deck',
  MEETINGS: 'Flight Review',
  MEETINGS_LONG: 'Weekly Flight Review',
  ORGANIZATIONS: 'Fleet',
  MEMBERS: 'Crew',
  TEAMS: 'Flight Crews',
  TODOS: 'Clearances',
  ROCKS: 'Waypoints',
  ISSUES: 'Turbulence',
  SCORECARD: 'Flight Desk',
  SEGUE: 'Pre-Flight',
  HEADLINES: 'Crew Headlines',
  CONCLUDE: 'Debrief',
  START_MEETING: 'Start Flight Review',
  FINISH_MEETING: 'Finish Flight Review',
  INVITE_CREW: 'Invite Crew Members',
  VIEW_CREW: 'View all crew',
  ORGANIZATION_MEMBERS: 'Fleet Crew',
  CURRENT_FLIGHT_CREW: 'Current Flight Crew',
  NO_MEETINGS_YET: 'No flight reviews yet',
  FLIGHT_REVIEW_HISTORY: 'flight review history',
  INSTRUMENT_TRENDS: 'Instrument Panel Trends',
  TOTAL_CLEARANCES: 'Total Clearances',
  OPEN_TURBULENCE: 'Open Turbulence',
  ACTIVE_WAYPOINTS: 'Active Waypoints',
  CREW_MEMBERS: 'Crew Members',
  PLANNING_BOARD: 'Flight Plan',
  COMPANY_WAYPOINTS: 'Company Waypoints',
  WAYPOINTS_BY_OWNER: 'Waypoints by owner',
} as const;

/** Section id -> display title */
export const SECTION_DISPLAY_TITLES: Record<string, string> = {
  segue: FLIGHT_TERMS.SEGUE,
  scorecard: FLIGHT_TERMS.SCORECARD,
  rocks: 'Waypoint Review',
  headlines: FLIGHT_TERMS.HEADLINES,
  todos: FLIGHT_TERMS.TODOS,
  issues: FLIGHT_TERMS.ISSUES,
  conclude: FLIGHT_TERMS.CONCLUDE,
};
