// Flight-based terminology for FlightDeck OS (display labels only; URLs unchanged)
export const FLIGHT_TERMS = {
  OVERVIEW: 'Flight Deck',
  MEETINGS: 'Flight Review',
  MEETINGS_LONG: 'Weekly Flight Review',
  ORGANIZATIONS: 'Fleet',
  MEMBERS: 'Crew',
  TEAMS: 'Flight Crews',
  TODOS: 'Clearances (To-Dos)',
  ROCKS: 'Waypoints (Rocks)',
  ISSUES: 'Turbulence (Issues)',
  SCORECARD: 'Instrument Panel (Scorecard)',
  START_MEETING: 'Start Flight Review',
  FINISH_MEETING: 'Finish Flight Review',
  INVITE_CREW: 'Invite Crew Members',
  VIEW_CREW: 'View all crew',
  ORGANIZATION_MEMBERS: 'Fleet Crew',
  CURRENT_FLIGHT_CREW: 'Current Flight Crew',
  NO_MEETINGS_YET: 'No flight reviews yet',
  FLIGHT_REVIEW_HISTORY: 'flight review history',
  INSTRUMENT_TRENDS: 'Instrument Panel Trends',
  TOTAL_CLEARANCES: 'Total Clearances',
  OPEN_TURBULENCE: 'Open Turbulence',
  ACTIVE_WAYPOINTS: 'Active Waypoints',
  CREW_MEMBERS: 'Crew Members',
} as const;
