// Route constants for FlightDeck
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  MEETING: (id: string) => `/meeting/${id}`,
  OVERVIEW: '/dashboard/overview',
  MEETINGS: '/dashboard/meetings',
  MEETINGS_UPCOMING: '/dashboard/meetings/upcoming',
  MEETINGS_PAST: '/dashboard/meetings/past',
  MEETINGS_AGENDAS: '/dashboard/meetings/agendas',
  MEETING_AGENDA_EDIT: (id: string) => `/dashboard/meetings/agendas/${id}`,
  ORGANIZATIONS: '/dashboard/organizations',
  ORGANIZATIONS_MEMBERS: '/dashboard/organizations/members',
  TEAMS: '/dashboard/teams',
  TODOS: '/dashboard/todos',
  ROCKS: '/dashboard/rocks',
  ISSUES: '/dashboard/issues',
  SCORECARD: '/dashboard/scorecard',
  HEADLINES: '/dashboard/headlines',
} as const;
